### ISSUE TITLE
Compile Fails on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/S8DS#5]
https://dpaste.org/oVotU

**Comment by Ntemis** [comment]
interesting :)
diff --git a/source/Gui.c b/source/Gui.c
index e2c2eb2..e319fdb 100644
--- a/source/Gui.c
+++ b/source/Gui.c
@@ -25,7 +25,7 @@
 #include "Sound.h"
 #include "ARMZ80/Version.h"
 #include "SN76496/Version.h"
-#include "SegaVDP/version.h"
+#include "SegaVDP/Version.h"
 #include "AY38910/Version.h"
 #include "SCC/Version.h"

**Comment by Ntemis** [comment]
Another one
diff --git a/source/Main.c b/source/Main.c
index cf9c9df..aeb599b 100644
--- a/source/Main.c
+++ b/source/Main.c
@@ -7,7 +7,7 @@
 #include "Shared/FileHelper.h"
 #include "Shared/AsmExtra.h"
 #include "Gui.h"
-#include "YM2413.h"
+#include "YM2413/YM2413.h"
 #include "FileHandling.h"
 #include "EmuFont.h"
 #include "Cart.h"

**Comment by Ntemis** [comment]
And the final fix is a success
diff --git a/source/RomLoading.c b/source/RomLoading.c
index 3a630c7..720ce66 100644
--- a/source/RomLoading.c
+++ b/source/RomLoading.c
@@ -10,7 +10,7 @@
 #include "FileHandling.h"
 #include "Gui.h"
 #include "Shared/FileHelper.h"
-#include "Shared/unzip/unzipnds.h"
+#include "Shared/Unzip/unzipnds.h"
 #include "Equates.h"
 #include "Cart.h"
 #include "io.h"

**Comment by Ntemis** [comment]
diff --git a/source/Gui.c b/source/Gui.c
index e2c2eb2..e319fdb 100644
--- a/source/Gui.c
+++ b/source/Gui.c
@@ -25,7 +25,7 @@
 #include "Sound.h"
 #include "ARMZ80/Version.h"
 #include "SN76496/Version.h"
-#include "SegaVDP/version.h"
+#include "SegaVDP/Version.h"
 #include "AY38910/Version.h"
 #include "SCC/Version.h"
 
diff --git a/source/Main.c b/source/Main.c
index cf9c9df..aeb599b 100644
--- a/source/Main.c
+++ b/source/Main.c
@@ -7,7 +7,7 @@
 #include "Shared/FileHelper.h"
 #include "Shared/AsmExtra.h"
 #include "Gui.h"
-#include "YM2413.h"
+#include "YM2413/YM2413.h"
 #include "FileHandling.h"
 #include "EmuFont.h"
 #include "Cart.h"
diff --git a/source/RomLoading.c b/source/RomLoading.c
index 3a630c7..720ce66 100644
--- a/source/RomLoading.c
+++ b/source/RomLoading.c
@@ -10,7 +10,7 @@
 #include "FileHandling.h"
 #include "Gui.h"
 #include "Shared/FileHelper.h"
-#include "Shared/unzip/unzipnds.h"
+#include "Shared/Unzip/unzipnds.h"
 #include "Equates.h"
 #include "Cart.h"
 #include "io.h"

**Comment by FluBBaOfWard** [comment]
Can you check my changes are working?

**Comment by Ntemis** [comment]
of course i can

**Comment by Ntemis** [comment]
Works fine , thank you
