### ISSUE TITLE
"Couldn't find folder: s8ds"

### ISSUE THREAD

**Issue by jimmijam10** [FluBBaOfWard/S8DS#8]
Can't save anything!!!

Also, the master system image in the bottom screen annoys me.

**Comment by jimmijam10** [comment]
And I get this issue both in a DS emulator and an actual DSI, so it's universal it seems.

**Comment by FluBBaOfWard** [comment]
This is not a support forum, there are other places for that.
There is a README included with the release, please read it before posting more "issues" here.
